### ISSUE TITLE
TypeError: getRandomGreeting is not a function

### ISSUE THREAD

**Issue by kanggeonnim** [kanggeonnim/LBDRWT#19]
node index.js를 실행시킨 후 greeting 함수를 실행시키기 위해 "hi"를 입력하면 오류가 발생후 모듈이 종료 됨.

 at greeting (/Users/kanggeon/workspace/OSS/chatbot/greeting/greeting.js:15:15)
    at RTMClient.<anonymous> (/Users/kanggeon/workspace/OSS/chatbot/index.js:42:5)
    at RTMClient.emit (/Users/kanggeon/workspace/OSS/chatbot/node_modules/eventemitter3/index.js:181:35)
    at RTMClient.onWebsocketMessage (/Users/kanggeon/workspace/OSS/chatbot/node_modules/@slack/rtm-api/dist/RTMClient.js:463:14)
    at WebSocket.onMessage (/Users/kanggeon/workspace/OSS/chatbot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/Users/kanggeon/workspace/OSS/chatbot/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/Users/kanggeon/workspace/OSS/chatbot/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/Users/kanggeon/workspace/OSS/chatbot/node_modules/ws/lib/receiver.js:346:17)

**Comment by flex2020** [comment]
확인해보니 머지가 잘 못 되었습니다.
머지 전으로 돌려서 다시 머지를 시켜봐야할 것 같습니다.
